name: Setup project
description: Prepare the project for any CI action

inputs:
  bun-version:
    description: Version of Bun to install
    default: latest

  node-version:
    description: Version of Node to install
    default: 20.x

runs:
  using: composite
  steps:
    - name: 🏗 Setup Node
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: 🏗 Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: 📦 Install dependencies
      run: bun install
      shell: bash

    - name: ♻️ Restore Metro cache
      if: ${{ inputs.with-webui == 'true' }}
      uses: actions/cache@v4
      with:
        key: metro-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          metro-${{ runner.os }}
        path: |
          packages/expo-atlas-ui/node_modules/.cache/metro
